name: epicpay
description: Epic Pay

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.13.0+45

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ^3.24.2

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  mutex: ^3.0.0

  flutter_libepiccash:
    path: ./crypto_plugins/flutter_libepiccash

#  firo_flutter:
#    git:
#      url: https://github.com/cypherstack/firo_flutter.git
#      ref: update
  #    path: ./crypto_plugins/firo_flutter

  bitcoindart:
    git:
      url: https://github.com/cypherstack/bitcoindart.git
      ref: af6d6c27edfe2e7cc35772ed2684eb4cc826f0e4

  stack_wallet_backup:
    git:
      url: https://github.com/cypherstack/stack_wallet_backup.git
      ref: ee1da8a9ba1cbeb50c5b354ea1fd5a25b7c5a3ed

  bip47:
    git:
      url: https://github.com/cypherstack/bip47.git
      ref: 081ca1863c2feba00c35bb5b297902f12f499941

  # Utility plugins
  http: ^0.13.0
  local_auth: ^1.1.10
  permission_handler: ^10.0.0
  dart_numerics: ^0.0.6

  # Bitcoin plugins
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 0cd6d54e2860bea68fc50c801cb9db2a760192fb

  # Storage plugins
  flutter_secure_storage: ^8.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # UI/Component plugins
  flutter_native_splash: ^2.2.4
  google_fonts: ^4.0.4
  url_launcher: ^6.0.5
  flutter_svg: ^1.0.1
  flutter_feather_icons: ^2.0.0+1
  decimal: ^2.1.0
  event_bus: ^2.0.0
  uuid: ^3.0.5
  flutter_rounded_date_picker: ^3.0.4
  crypto: ^3.0.2
  barcode_scan2: ^4.2.3
  wakelock: ^0.6.2
  intl: ^0.17.0
  devicelocale: ^0.6.0
  device_info_plus: ^9.0.2
  keyboard_dismisser: ^3.0.0
  tuple: ^2.0.0
  flutter_riverpod: ^1.0.3
  qr_flutter: 4.0.0
  share_plus: ^7.0.2
  package_info_plus: ^4.0.2
  lottie: ^2.3.2
  file_picker: ^5.3.1
  connectivity_plus: ^4.0.1
  isar: 3.0.5
  isar_flutter_libs: 3.0.5 # contains the binaries
  dropdown_button2: ^2.1.3
  string_validator: ^0.3.0
  web_socket_channel: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
      sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0
  dependency_validator: ^3.1.2
  hive_test: ^1.0.1
  mockito: ^5.4.1
  mockingjay: ^0.2.0
#  lint: ^1.10.0
  analyzer: ^5.13.0
  import_sorter: ^4.6.0
  flutter_lints: ^2.0.1
  isar_generator: 3.0.5

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  image_path_android: assets/icon/app_icon_alpha.png
  adaptive_icon_foreground: assets/icon/app_icon_alpha.png
  image_path_ios: assets/icon/icon.png
  adaptive_icon_background: "#222227"
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/splash.png
  color: "222227"
  android_disable_fullscreen: true

dependency_overrides:
  # required for dart 3, at least until a fix is merged upstream
  wakelock_windows:
    git:
      url: https://github.com/diegotori/wakelock
      ref: 2a9bca63a540771f241d688562351482b2cf234c
      path: wakelock_windows

  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 0cd6d54e2860bea68fc50c801cb9db2a760192fb
  crypto: 3.0.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/epic-fast.png
    - assets/images/epic-clouds.png
    - assets/images/epic-welcome.png
    - assets/images/splash.png
    - assets/icon/icon.png

    - google_fonts/
    - assets/svg/circle-check.svg
    - assets/svg/plus.svg
    - assets/svg/gear.svg
    - assets/svg/bell.svg
    - assets/svg/arrow-left-fa.svg
    - assets/svg/copy.svg
    - assets/svg/check.svg
    - assets/svg/alert-circle.svg
    - assets/svg/arrow-down-left.svg
    - assets/svg/arrow-up-right.svg
    - assets/svg/bars.svg
    - assets/svg/filter.svg
    - assets/svg/arrow-rotate.svg
    - assets/svg/arrow-rotate2.svg
    - assets/svg/qrcode1.svg
    - assets/svg/gear-3.svg
    - assets/svg/swap.svg
    - assets/svg/chevron-down.svg
    - assets/svg/chevron-up.svg
    - assets/svg/lock-filled.svg
    - assets/svg/unlocked.svg
    - assets/svg/lock.svg
    - assets/svg/globe.svg
    - assets/svg/wifi.svg
    - assets/svg/book-open.svg
    - assets/svg/folder-down.svg
    - assets/svg/network-wired-2.svg
    - assets/svg/arrow-right.svg
    - assets/svg/delete.svg
    - assets/svg/dollar-sign.svg
    - assets/svg/sun-bright2.svg
    - assets/svg/language2.svg
    - assets/svg/magnifying-glass.svg
    - assets/svg/x.svg
    - assets/svg/user.svg
    - assets/svg/trash.svg
    - assets/svg/eye.svg
    - assets/svg/eye-slash.svg
    - assets/svg/folder.svg
    - assets/svg/calendar-days.svg
    - assets/svg/circle-question.svg
    - assets/svg/info-circle.svg
    - assets/svg/key.svg
    - assets/svg/node-alt.svg
    - assets/svg/ellipsis-vertical1.svg
    - assets/svg/dice-alt.svg
    - assets/svg/circle-arrow-up-right2.svg
    - assets/svg/loader.svg
    - assets/svg/dark/tx-icon-send.svg
    - assets/svg/dark/tx-icon-send-pending.svg
    - assets/svg/dark/tx-icon-send-failed.svg
    - assets/svg/dark/tx-icon-receive.svg
    - assets/svg/dark/tx-icon-receive-pending.svg
    - assets/svg/dark/tx-icon-receive-failed.svg
    - assets/svg/dark/arrow-down-circle-pending.svg
    - assets/svg/dark/arrow-up-circle-pending.svg
    - assets/svg/add-backup.svg
    - assets/svg/auto-backup.svg
    - assets/svg/message-question.svg
    - assets/svg/envelope.svg
    - assets/svg/dollar-sign-circle.svg
    - assets/svg/language-circle.svg
    - assets/svg/sun-circle.svg
    - assets/svg/node-circle.svg
    - assets/svg/about-desktop.svg
    - assets/svg/exchange-desktop.svg
    - assets/svg/exit-desktop.svg
    - assets/svg/keys.svg
    - assets/svg/arrow-down.svg
    - assets/svg/thin-x-circle.svg
    - assets/svg/check-circle.svg
    - assets/svg/epic-bg.svg
    - assets/svg/upload.svg
    - assets/svg/download.svg
    - assets/svg/eye-off.svg
    - assets/svg/edit.svg
    - assets/svg/refresh.svg
    - assets/svg/clipboard.svg
    - assets/svg/swap-arrows.svg
    - assets/svg/tx-swap.svg
    - assets/svg/tx-swap-pending.svg
    # coin icons
    - assets/svg/coin_icons/EpicCash.svg
    # socials
    - assets/svg/socials/compass.svg
    - assets/svg/socials/reddit.svg
    - assets/svg/socials/twitter.svg
    - assets/svg/socials/telegram.svg

    - assets/svg/chevron-right.svg
    - assets/svg/exchange-3.svg
    - assets/svg/message-question-1.svg
    - assets/svg/drd-icon.svg
    - assets/svg/box-auto.svg
    - assets/svg/wallet.svg
    - assets/svg/change-now-logo.svg
    - assets/svg/pay.svg
    - assets/svg/buy-credit-card.svg
    - assets/svg/bitcoin.svg
    - assets/svg/dollar.svg
    - assets/svg/paste.svg

    - assets/svg/layers/
    - assets/svg/cn_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/test\/*
    - \/crypto_plugins\/*
    - \/integration_test\/*
